### ISSUE TITLE
Bump to gatsby 2.0

### ISSUE THREAD

**Issue by richsoni** [barskern/gatsby-plugin-pathdata#1]
Hey,

I use this plugin, and just upgraded to gatsby 2.0, and I get this warning:

```
warning Plugin gatsby-plugin-pathdata is not compatible with your gatsby version 2.0.59 - It requires gatsby@1.x
```

My site still works fine, so I think the dependency needs to be bumped.

**Comment by barskern** [comment]
Yeah I sat `gatsby v1.x` as the peer dependency so it's only a matter of updating the `package.json`. I will do it and publish a new version. Thank you for notifying me! 😊

**Comment by richsoni** [comment]
you got it

**Comment by barskern** [comment]
v1.1.0 is now updated to require gatsby 2.x.

**Comment by richsoni** [comment]
Thanks!!!
